remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-cayman

github:
  is_project_page: false

title: Colloquium Joost-Pieter Katoen
description: Joost-Pieter in Logic Lane, Oxford
show_downloads: false
logo: logo.jpeg
